
all:
	./script/make_dataset.sh
	./script/compute_metrics.sh

prepare:
	./script/make_dataset.sh

compute:
	./script/compute_metrics.sh

clean:
	rm work/198*.txt
	rm result/198*.result
	rm work/199*.txt
	rm result/199*.result
	rm work/200*.txt
	rm result/200*.result
